FROM python:3.11-slim-bookworm AS builder

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    git \
    curl \
    ca-certificates \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Go tools (subfinder, httpx, etc.)
ENV GO_VERSION=1.25.11
RUN curl -fsSL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz | tar -xz -C /usr/local
ENV GOPATH=/go
ENV PATH="/usr/local/go/bin:${GOPATH}/bin:${PATH}"
ENV GOPROXY=https://proxy.golang.org,direct

# Pin every Go tool to a specific verified version.
# To upgrade: change the version tag, rebuild, test, commit.
# @latest is NEVER used — it breaks reproducible builds and
# opens the door to supply-chain attacks on any future build.
RUN go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@v2.6.6 && \
    go install -v github.com/projectdiscovery/httpx/cmd/httpx@v1.6.10 && \
    go install -v github.com/projectdiscovery/katana/cmd/katana@v1.1.0 && \
    go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@v3.2.9 && \
    go install -v github.com/tomnomnom/assetfinder@v0.1.1 && \
    go install -v github.com/tomnomnom/waybackurls@v0.1.0 && \
    go install -v github.com/lc/gau/v2/cmd/gau@v2.2.3 && \
    go install -v github.com/tomnomnom/unfurl@v0.4.3 && \
    go install -v github.com/tomnomnom/qsreplace@v0.0.3 && \
    go install -v github.com/hahwul/dalfox/v2@v2.9.2 && \
    go install -v github.com/PentestPad/subzy@latest && \
    go install -v github.com/BishopFox/jsluice/cmd/jsluice@latest

# Build trufflehog manual (karena ada replace directive di go.mod-nya)
RUN git clone https://github.com/trufflesecurity/trufflehog.git /tmp/trufflehog && \
    cd /tmp/trufflehog && \
    git checkout v3.95.6 && \
    go build -o ${GOPATH}/bin/trufflehog . && \
    rm -rf /tmp/trufflehog

# ─────────────────────────────────────────────────────────────
# Final stage
# ─────────────────────────────────────────────────────────────
FROM python:3.11-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# ============ PERBAIKAN 1 ============
# Copy semua binary Go dari /go/bin (bukan /root/go/bin)
COPY --from=builder /go/bin /usr/local/bin
# =====================================

COPY --from=builder /usr/local/go /usr/local/go
ENV PATH="/usr/local/go/bin:${PATH}"

# ============ PERBAIKAN 2 ============
# Install uro (Python) langsung di sini
RUN pip install uro
# =====================================

WORKDIR /app

# Install Python dependencies from hash-verified lockfile.
# requirements.lock is generated by:
#   pip-compile --generate-hashes requirements.txt --output-file requirements.lock
COPY requirements.txt requirements.lock requirements-dev.txt ./
RUN pip install --no-cache-dir --require-hashes -r requirements.lock

# Copy application code
COPY python/ ./python/
COPY bash/ ./bash/
COPY sql/ ./sql/
COPY scripts/ ./scripts/
COPY .env.example ./.env

# Create directories
RUN mkdir -p /app/output /app/logs

# Set permissions
RUN chmod +x ./scripts/*.sh ./bash/wrappers/*.sh ./bash/lib/*.sh

# Create a non-root user and group, then hand over ownership
RUN groupadd -r appuser && \
    useradd -r -g appuser -d /app -s /sbin/nologin -c "App user" appuser && \
    chown -R appuser:appuser /app

# Drop root — all subsequent RUN, CMD, ENTRYPOINT run as appuser
USER appuser

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD ./scripts/healthcheck.sh

CMD ["python", "-m", "python.main"]